#!/bin/sh -e
# used for initramfs
export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
. /lib/debian-installer/init-debug
debugshell "just booted"

mkdir -p /run
mount /run
mkdir -p /run/lock /proc /sys
mount /proc
mount /sys
#echo "Running start-udev..."
#/lib/debian-installer/start-udev
echo "Running /sbin/init..."

init='/bin/busybox init'
for i in $(cat /proc/cmdline); do
	case $i in
		init=/init|init=init)
			# Avoid endless loop
			: ;;
		init=*)
			init=${i#init=} ;;
		noshell)
			sed -i '/^tty[23]/s/^/#/' /etc/inittab ;;
	esac
done
debugshell "before init"
exec $init
