#!/bin/sh -e
# Set up filesystem as root and pivot into it.
export PATH
. /lib/debian-installer/init-debug
debugshell "just booted"

echo "Setting up filesystem, please wait ..."

mount /proc
umount initrd 2>/dev/null || true
if mount -t tmpfs -o size=100M tmpfs /mnt ; then
	:
elif mount -t shm shm mnt; then
	:
else
	mount -t ramfs ramfs /mnt
fi
umount /proc
cp -a $(ls -1 / | grep -v '\(lost+found\|mnt\|proc\)') /mnt
cd /mnt
pivot_root . initrd
mkdir -p /proc
mount /proc
mkdir -p /sys
mount /sys

# kill off the || true's once this is tested FIXME
/etc/init.d/udev start || true
mknod -m 666 /dev/tty c 5 0 || true
mknod -m 640 /dev/tty1 c 4 1 || true
mknod -m 666 /dev/vcs c 7 0 || true
mknod -m 660 /dev/vcs1 c 7 1 || true
# end experiment
/lib/debian-installer/start-udev

# Close all open files on the initrd, and run busybox init.
debugshell "before init"
exec /usr/sbin/chroot . /bin/busybox init < /dev/console > /dev/console 2>&1
