#!/bin/sh
# Set up filesystem as root and pivot into it.
export PATH
. /lib/debian-installer/init-debug
debugshell "just booted"

echo "Setting up filesystem, please wait ..."

umount initrd 2>/dev/null || true
if mount -t tmpfs -o size=100M tmpfs /mnt ; then
	:
elif mount -t shm shm mnt; then
	:
else
	mount -t ramfs ramfs /mnt
fi
umount /proc
cp -a $(ls -1 / | grep -v '\(lost+found\|mnt\|proc\)') /mnt
cd /mnt
pivot_root . initrd
mkdir -p /proc
mount /proc
mkdir -p /sys
mount /sys

#/lib/debian-installer/start-udev launched by /init
# kill off the " || true"'s once this is tested FIXME
for i in /dev /mnt/dev ; do
	mkdir -p $i
	mknod -m 640 $i/mem c 1 1 || true
	mknod -m 666 $i/null c 1 3 || true
	mknod -m 666 $i/port c 1 4 || true
	mknod -m 666 $i/zero c 1 5 || true
	mknod -m 666 $i/random c 1 8 || true
	mknod -m 666 $i/urandom c 1 9 || true
	mknod -m 666 $i/tty c 5 0 || true
	mknod -m 600 $i/console c 5 1 || true
	mknod -m 640 $i/tty1 c 4 1 || true
	mknod -m 640 $i/tty2 c 4 1 || true
	mknod -m 640 $i/tty3 c 4 1 || true
	mknod -m 640 $i/tty4 c 4 1 || true
	mknod -m 640 $i/tty5 c 4 1 || true
	mknod -m 640 $i/tty6 c 4 1 || true
	mknod -m 640 $i/tty7 c 4 1 || true
	mknod -m 640 $i/tty8 c 4 1 || true
	mknod -m 640 $i/tty9 c 4 1 || true
	mknod -m 666 $i/vcs c 7 0 || true
	mknod -m 660 $i/vcs1 c 7 1 || true
	mknod -m 660 $i/vcs2 c 7 2 || true
	mknod -m 660 $i/vcs3 c 7 3 || true
	mknod -m 660 $i/vcs4 c 7 4 || true
	mknod -m 660 $i/vcs5 c 7 5 || true
	mknod -m 660 $i/vcs6 c 7 6 || true
done
mkdir -p /var/run/console-device
if [ ! -r /var/run/console-device ] ; then
	echo /dev/console > /var/run/console-device
fi
mkdir -p /mnt/var/run/console-device
if [ ! -r /mnt/var/run/console-device ] ; then
	echo /dev/console > /mnt/var/run/console-device
fi
# end experiment

# Close all open files on the initrd, and run busybox init.
debugshell "before init"
exec /usr/sbin/chroot . /bin/busybox init < /dev/console > /dev/console 2>&1
